# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.24.1
    hooks:
      - id: validate-pyproject
        name: validate-pyproject

  - repo: https://github.com/dosisod/refurb
    rev: v2.1.0
    hooks:
      - id: refurb
        name: refurb

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.12.12
    hooks:
      - id: ruff
        name: ruff lint
        args: ["--fixable=I","--fix"]
      - id: ruff-format
        name: ruff format

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint
        name: markdownlint

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.22
    hooks:
      - id: mdformat
        name: mdformat-ruff
        additional_dependencies:
          - mdformat-ruff
          - ruff

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.15
    hooks:
      - id: uv-lock
      - id: uv-export
        args: ["--frozen", "--output-file=pylock.toml", "--quiet"]
