blank_issues_enabled: true
contact_links:
  - name: Have a general question?
    url: https://github.com/OMEGARAZER/prowlpy/discussions
    about: Have questions about Prowlpy, ask anything you like on the discussions board
