name: Python Test

on:
  push:
    paths:
      - "**.py"
  pull_request:
    paths:
      - "**.py"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
    - uses: actions/checkout@v5
    - name: Setup UV
      uses: astral-sh/setup-uv@v7
      with:
        python-version: ${{ matrix.python-version }}
        version: "latest"

    - name: Test with pytest on ${{ matrix.python-version }}
      run: |
        uv sync --frozen --all-groups
        uv run --frozen pytest --verbose --cov=./prowlpy/ --cov-branch --cov-report html --cov-report xml

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Upload coverage report
      uses: actions/upload-artifact@v5
      with:
        name: coverage_report-${{ matrix.os }}-${{ matrix.python-version }}
        path: htmlcov/
